require: rubocop-rspec

inherit_from:
  - .rubocop_todo.yml

AllCops:
  Exclude:
  - "lib/generators/blacklight/templates/**/*"
  - "spec/**/*"
  - "blacklight.gemspec"

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 200

Style/StringLiterals:
  Enabled: false

Style/IndentationConsistency:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Style/MethodMissing:
  Exclude:
  - 'lib/blacklight/utils.rb'
