notifications:
  email: false

rvm:
  - 1.9.3
  - jruby-19mode
  - 2.0.0

gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails4.gemfile

notifications:
  irc: "irc.freenode.org#blacklight"
  email:
      - blacklight-commits@googlegroups.com

# jruby 1.9 + rails 4.0.0.beta1 don't work well together
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - gemfile: gemfiles/rails4.gemfile
