notifications:
  email: false

rvm:
  - 2.1.1

before_install:
  - gem install bundler --version '~> 1.6.2'

gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails4.gemfile
  - gemfiles/rails4.1.gemfile

matrix:
  include:
    - rvm: 2.1.0
      gemfile: gemfiles/rails4.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails4.gemfile
    - rvm: jruby
      gemfile: gemfiles/rails4.gemfile

notifications:
  irc: "irc.freenode.org#blacklight"
  email:
      - blacklight-commits@googlegroups.com

env: JRUBY_OPTS="-J-Xms512m -J-Xmx1024m"        
