sudo: false
language: ruby
rvm:
  - 2.2.5
gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails4.gemfile
  - gemfiles/rails4.1.gemfile

matrix:
  include:
    - rvm: 2.3.1
      gemfile: gemfiles/rails4.1.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails4.1.gemfile

notifications:
  irc: "irc.freenode.org#blacklight"
  email: false

env: JRUBY_OPTS="-J-Xms512m -J-Xmx1024m"
