dist: trusty
language: ruby
cache:
  bundler: true
  directories:
    - .internal_test_app

sudo: required

notifications:
  email: false

services:
  - docker

rvm:
  - 2.4.1

matrix:
  include:
    - rvm: 2.3.3
      env: "RAILS_VERSION=5.1.1"
    - rvm: jruby-9.1.7.0
      env: "RAILS_VERSION=5.0.3 JRUBY_OPTS=\"-J-Xms512m -J-Xmx1024m\""
  allow_failures:
    - rvm: jruby-9.1.7.0
  fast_finish: true

before_install:
  - gem update --system
  - gem install bundler
  - docker run --name my_solr -d -p 8983:8983 solr
  - docker cp ./solr/conf my_solr:/opt/solr/blacklight-solr-conf
  - sleep 10; docker exec -it --user=solr my_solr bin/solr create_core -c blacklight-core -d /opt/solr/blacklight-solr-conf

env:
 - "RAILS_VERSION=5.0.3"

notifications:
  irc: "irc.freenode.org#blacklight"
  email:
      - blacklight-commits@googlegroups.com

global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

jdk: oraclejdk8
