language: ruby
sudo: false

notifications:
  email: false

rvm:
  - 2.3.1

matrix:
  include:
    - rvm: 2.3.1
      env: "RAILS_VERSION=4.2.6"
    - rvm: 2.2.5
      env: "RAILS_VERSION=5.0.0"
    - rvm: jruby-9.0.5.0
      env: "RAILS_VERSION=4.2.6 JRUBY_OPTS=\"-J-Xms512m -J-Xmx1024m\""
  allow_failures:
    - rvm: jruby-9.0.5.0
  fast_finish: true

before_install:
  - gem uninstall -i /home/travis/.rvm/gems/ruby-`ruby -e 'puts RUBY_VERSION'`@global bundler -v 1.13.0
  - gem install bundler -v 1.12.5

env:
 - "RAILS_VERSION=5.0.0"

notifications:
  irc: "irc.freenode.org#blacklight"
  email:
      - blacklight-commits@googlegroups.com

global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

jdk: oraclejdk8
